### ISSUE TITLE
how to handle background-images in .css file

### ISSUE THREAD

**Issue by Jogiter** [egoist/rollup-plugin-postcss#118]
if i had a css file like below

```css
.foo{
  background: url(../logo.png) no-repeat -6px -27px;
}
.bar{
  background: url(../logo.png) no-repeat -7px -28px;
}
```

how can i transform those url to base64, and i`ll want the same image load once
