### ISSUE TITLE
Multiple imports creates duplicates.

### ISSUE THREAD

**Issue by DylanPiercey** [egoist/rollup-plugin-postcss#26]
This issue is specifically tied to the `postcss-modules` plugin but I am not sure if the issue is located here. Let me know if otherwise.

Given the following js file:

```js
import './style1.css'
import './style2.css'
```

With the following css files:

*style1.css*
```css
.style1 {
  composes: style2 from "./style2.css";
  color: gold;
}
```

*style2.css*
```css
.style2 {
  background: green;
}
```

`style2.css` gets duplicated since it is composed and imported (seems to be treated separately).

Can you think of a way around this?
