### ISSUE TITLE
compiled sass not in generated bundle when using modules

### ISSUE THREAD

**Issue by dagda1** [egoist/rollup-plugin-postcss#327]
I am using sass and css modules and my config looks like this:

```ts
      postcss({
        extract: false,
        modules: true,
        use: ['sass'],
        sourceMap: true,
      }),
```

Which works for the most part but I have a sass file without any actual classes and looks a bit like this

```scss
html {
  min-height: 100%;
  height: 100%;
}

body {
  height: 100%;
  background-color: $body-bg;
}

:global #root {
  height: 100%;
  display: flex;
  flex-direction: column;
  flex: 1 0 auto;
}
```

None of this ends up in the generated bundle.

Is there anything I can do to correct this?

I think at the moment anything that is not a class is getting treated as dead code and getting stripped.
