### ISSUE TITLE
Empty classes get stripped out

### ISSUE THREAD

**Issue by FezVrasta** [egoist/rollup-plugin-postcss#35]
I have a CSS like the following:

```css
.Foo {
}
.Foo__bar {
  color: red;
}
```

When I import this with `postcss-modules` I only get:

```js
{ Foo__bar: 'Foo__bar_xxxx' }
```

The empty `Foo` is lost.
