### ISSUE TITLE
Weird text overriding

### ISSUE THREAD

**Issue by eddow** [egoist/rollup-plugin-postcss#405]
I'm trying `-postcss` instead of `-css-only` to try to solve another problem, but I face this one here.

With this configuration: 
```js
{
...
		scss(),
		vue({
			css: false
		}),
		postcss({
			extract: true,
			sourceMap: true
		}),
...
}
```

this is the begining of the generated `index.css` file :
```css











/*# sourceMappingURL=index.css.map */gleapis.com/css2?family=Lato:ital,wght@0,400%3B0,700%3B1,400%3B1,700&subset=latin&display=swap");
.body {
  overflow: hidden;
}
.....
```

The first non-empty line is on line 12.

Without source-mapping, this is the beginning:

```css










UTF-8";
@import url("https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400%3B0,700%3B1,400%3B1,700&subset=latin&display=swap");
.body {
  overflow: hidden;
}
.....
```

PS: I tried with `3.0.0` and `4.0.2`
