### ISSUE TITLE
Plugins run twice on css modules

### ISSUE THREAD

**Issue by pascalduez** [egoist/rollup-plugin-postcss#70]
Hi,

I'm still investigating the issue but wanted some feedback:

```js
postcss({
  modules: true,
  extract: true,
  plugins: [
    require('postcss-custom-properties')({ preserve: true })
  ],
})
```
Result:

```css
.Button_primary__1gH9y {
  color: green;
  color: green;
  color: var(--color-primary);
}
```

I did some logging and the `postcss-custom-properties` is run twice on the same css module, hence the duplicate fallback.

1st
```css
.primary {
  color: var(--color-primary);
}
```
2nd
```css
.Button_primary__1gH9y {
  color: green;
  color: var(--color-primary);
}
```

**Comment by pascalduez** [comment]
Ok, narrowed to css-modules/postcss-modules/issues/70

**Comment by pascalduez** [comment]
Also using CSS modules composition could result in a bunch of duplicate rules.

```css
/* Shared.css */
.test {
  content: 'test';
}

/* Foo.css */
.foo {
  composes: test from './Shared.css';
}

/* Bar.css */
.bar {
  composes: test from './Shared.css';
}
```

Result:

```css
.Shared-test {
  content: 'test';
}

.Foo-foo {}

.Shared-test {
  content: 'test';
}

.Bar-bar {}
```

**Comment by peter-mouland** [comment]
I ran into this issue today, was there a fix for this?

**Comment by n370** [comment]
@peter-mouland my solution was  to use `postcss-modules` explicitly. As soon as I get some time I'll look into putting a PR together fixing this issue.

```
    plugins: [
        postcss({
            extract: false,
            minimize: true,
            use: ['sass'],
            plugins: [
                postcssModules()
            ]
        })
    ],
```

**Comment by n370** [comment]
I found that changing https://github.com/egoist/rollup-plugin-postcss/blob/master/src/postcss-loader.js#L75 from `push` to `unshift` fixes the issue.

**Comment by Anidetrix** [comment]
it also breaks such plugins as postcss-import, cause imported classes won't be modularized

**Comment by Anidetrix** [comment]
@n370 this change breaks such plugins as postcss-import, cause imported classes won't be modularized

**Comment by n370** [comment]
@Anidetrix yeah, you're right. We need to find a better solution. One easy solution I can think of is to maybe add a hardcoded list of plugin names that need to be loaded before postcss-modules and then split the user provided list of plugins into a list of plugins to be loaded before postcss-modules and a list to be loaded after. But really that's my naive take since I have just a small experience with the codebase.

**Comment by Anidetrix** [comment]
@n370 This is due to the fact that postcss-modules calls PostCSS inside itseft, thus causing the doubing. The proper solution is to adapt separate PostCSS plugins as it is done in webpack's css-loader.

**Comment by n370** [comment]
@Anidetrix I haven't observed that behavior in my use case but that might be the case. Anyways, I was thinking about why one would want to use the postcss-import plugin when they already have sass, less and stylus built in.

**Comment by Anidetrix** [comment]
@n370 probably with something like SugarSS

**Comment by n370** [comment]
got you!

**Comment by pascalduez** [comment]
The issue is still alive: `rollup-plugin-postcss@3.1.4`

**Comment by danny-andrews** [comment]
Can confirm, I still see this issue on 3.1.8.

When I use `composes: classname from "./some-module.js"`, I end up with that rule being duplicated in the css output.

```css
.css_center-contents_fw {
  align-items: center;
  display: flex;
  justify-content: center;
}
```
